### ISSUE TITLE
check_status job fails sometimes

### ISSUE THREAD

**Issue by yachang** [m-lab/mlab-ns#136]
log is like:

object of type 'SliverTool' has no len() (/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py:1553)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~mlab-nstesting/20180508t192504.409580834790738648/mlabns/handlers/update.py", line 434, in get
    slice_info.address_family)
  File "/base/data/home/apps/s~mlab-nstesting/20180508t192504.409580834790738648/mlabns/handlers/update.py", line 450, in update_sliver_tools_status
    all_slivers=True))
  File "/base/data/home/apps/s~mlab-nstesting/20180508t192504.409580834790738648/mlabns/db/sliver_tool_fetcher.py", line 161, in fetch
    results = self._memcache_fetcher.fetch(tool_properties)
  File "/base/data/home/apps/s~mlab-nstesting/20180508t192504.409580834790738648/mlabns/db/sliver_tool_fetcher.py", line 205, in fetch
    tool_properties.tool_id, len(sliver_tools)))
TypeError: object of type 'SliverTool' has no len()

I see this failure on mlab-nstesting

**Comment by kokosta** [comment]
Obsolete. Believed to be fixed in latest release.
