### ISSUE TITLE
tool_extra datastore field grows out of control

### ISSUE THREAD

**Issue by nkinkade** [m-lab/mlab-ns#151]
The `check_status` cron job is failing with an exception:

```
Property tool_extra is 1508 bytes long; it must be 1500 or less.
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~mlab-ns/20180613t224831.410419053361130777/mlabns/handlers/update.py", line 411, in get
    slice_info.address_family)
  File "/base/data/home/apps/s~mlab-ns/20180613t224831.410419053361130777/mlabns/handlers/update.py", line 481, in update_sliver_tools_status
    slice_status[sliver_tool.fqdn]['tool_extra']
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 617, in __set__
    value = self.validate(value)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/be731db3a3e23b1a/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 2855, in validate
    % (self.name, len(value), self.MAX_LENGTH))
BadValueError: Property tool_extra is 1508 bytes long; it must be 1500 or less.
```

If you browse through the datastore for kind `SliverTool` you find `tool_extra` fields with values like this:

`All TCP ports listening.(Family "_ipv6" for sliver not known by monitoring).(Family "_ipv6" for sliver not known by monitoring).(Family "_ipv6" for sliver not known by monitoring).(Family "_ipv6" for sliver not known by monitoring).`

This is being caused by [a bug in `handlers/update.py`](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/handlers/update.py#L442) where status is getting appended to `tool_extra` over and over, causing the data in the field to grow out of control with repeated values.

**Comment by nkinkade** [comment]
This was resolved by PR #152. Closing
