### ISSUE TITLE
NPAD is failing to perform redirects

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#38]
@nkinkade reported that mlab-ns is failing to redirect for NPAD.

http://mlab-ns.appspot.com/npad?format=redirect

Seems to be a missed unicode->str conversion someplace.
```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1547, in __call__
    return response(environ, start_response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webob-1.1.1/webob/response.py", line 939, in __call__
    start_response(self.status, headerlist)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/appstats/recording.py", line 1284, in appstats_start_response
    return start_response(status, headers, exc_info)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 200, in _StartResponse
    (_GetTypeName(value), value, name))
InvalidResponseError: header values must be str, got 'unicode' (u'http://npad.iupui.mlab2.nuq04.measurement-lab.org:8000') for 'Location'
```

**Comment by critzo** [comment]
Bumping this thread since it was just reported again by a user who emailed support. @mtlynch @fernandalavalle

**Comment by mtlynch** [comment]
Bumping because we got an additional report of a user running into this

**Comment by critzo** [comment]
We have received another report of board failing to run because of this bug. @fernandalavalle
